version: '3.5'

services:
  php-apache:
    container_name: php-apache
    build:
      context: .
      dockerfile: Dockerfile
    ports:
        - '8080:80'
    volumes:
      - ./src:/var/www/laravel_docker
      - ./apache/default.conf:/etc/apache2/sites-enabled/000-default.conf
